// <auto-generated />
using Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129170000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("SaldoAntes")
                        .HasColumnType("int");

                    b.Property<int>("SaldoDepois")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CodigoProduto")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProduto", "DataHora")
                        .HasDatabaseName("IX_Movimentacao_Codigo_DataHoraDesc")
                        .IsDescending(false, true);

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("MovimentacaoEstoque");
                });

            modelBuilder.Entity("Backend.Models.Produto", b =>
                {
                    b.Property<long>("Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Codigo");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Codigo = 101L,
                            Descricao = "Caneta Azul",
                            Estoque = 150
                        },
                        new
                        {
                            Codigo = 102L,
                            Descricao = "Caderno Universitário",
                            Estoque = 75
                        },
                        new
                        {
                            Codigo = 103L,
                            Descricao = "Borracha Branca",
                            Estoque = 200
                        },
                        new
                        {
                            Codigo = 104L,
                            Descricao = "Lápis Preto HB",
                            Estoque = 320
                        },
                        new
                        {
                            Codigo = 105L,
                            Descricao = "Marcador de Texto Amarelo",
                            Estoque = 90
                        });
                });

            modelBuilder.Entity("Backend.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Backend.Models.Produto", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("CodigoProduto")
                        .IsRequired()
                        .HasConstraintName("FK_Movimentacao_Produto");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Backend.Models.Produto", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
